spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/gighub}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-expiry: 3600000    # 1 hour
  refresh-expiry: 604800000  # 7 days

logging:
  level:
    com.gighub: DEBUG
    org.springframework: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.jdbc.env.internal: DEBUG

server:
  port: ${PORT:8080}

cors:
  allowed-origins: ${FRONTEND_URL}
